create table `trend` (
`id` int not null primary key auto_increment,
`text` text not null,
`last_updated_date` datetime not null,
`generated_date` datetime not null,
`newest_tweet_volume` mediumint,
`max_tweet_volume` mediumint,
`average_tweet_volume` mediumint,
`max_retweet` mediumint,
`max_favorite` mediumint,
`rank1` smallint,
`rank2` smallint,
`rank3` smallint,
`rank4` smallint,
`rank5` smallint,
`rank6` smallint,
`rank7` smallint,
`rank8` smallint,
`rank9` smallint,
`rank10` smallint,
`rank11` smallint,
`rank12` smallint,
`rank13` smallint,
`rank14` smallint,
`rank15` smallint,
`rank16` smallint,
`rank17` smallint,
`rank18` smallint,
`rank19` smallint,
`rank20` smallint,
`rank21` smallint,
`rank22` smallint,
`rank23` smallint,
`rank24` smallint,
`rank25` smallint,
`rank26` smallint,
`rank27` smallint,
`rank28` smallint,
`rank29` smallint,
`rank30` smallint,
`rank31` smallint,
`rank32` smallint,
`rank33` smallint,
`rank34` smallint,
`rank35` smallint,
`rank36` smallint,
`rank37` smallint,
`rank38` smallint,
`rank39` smallint,
`rank40` smallint,
`rank41` smallint,
`rank42` smallint,
`rank43` smallint,
`rank44` smallint,
`rank45` smallint,
`rank46` smallint,
`rank47` smallint,
`rank48` smallint,
`rank49` smallint,
`rank50` smallint,
`promoted_content` text,
`query` text
);
